endlessm/libingester

previewer/preview_renderer.js

The logic for current and new source display status is inverted, thus
first click on Flip button does nothing. This is fixed by having the
showingSource variable reflect the requested state in flipPage.

Fix previewer source/preview switch

---

examples/word_of_day.js
lib/index.js

There is already a 'set_synopsis' method on NewsArticle's parent, BaseAsset. Therefore, I don't see any need to add any 'synopsis' related methods to NewsArticle, or the need to export any 'synopsis' related metadata in NewsArticle. If I'm overlooking something, please advise. My other line of thinking was to handle a !synopsis issue at the time of ingestion, but I'm going to hold on that for now.

Remove any 'synopsis' related code from NewsArticle class

---

previewer/main.html

Old code only worked properly when running from the libingester directly
but failed when run as a dependency since paths are different. We now
account for that and try to load either of the stylesheets paths so we
work on both setups.

Make bootstrap css be resolvable if we're imported as a library

---

lib/index.js

Without this, it's really a pain to manage the hatch folders so now wei
add a timestamp instead of a random string to it.

Made libingester use timestamped directory names

---

package.json

With the article formats being merged, this is an API break. We have
already dubbed the article formats "Libingester 2" in conversations, so
it makes sense to bump to that version.
https://phabricator.endlessm.com/T17387

Bump to version 2.0.0

---

previewer/css/styles.css
previewer/main.html
previewer/main_renderer.js
previewer/preview_renderer.js

Since CSS can now be in the article, we needed to isolate it with an
iframe to not mess up the app styling. Fix for thumbnail on articles is
also included here.

Add support for libingester 2.0 hatch previews

---

previewer/css/styles.css

Old green color just didn't look correctly with the rest of the
application.

Libingester: Made colors of code view border match the Flip button

---

lib/assets/_media_link.scss
lib/assets/blog-stylesheet.scss
lib/assets/news-stylesheet.scss
lib/index.js
lib/util.js
test/lib/util.test.js

Instead of video tags, videos will now simply be links pointing to the
ingested video, with an image of that video's thumbnail. db-build
generates thumbnails if they're not provided, so one is not strictly
necessary.
https://phabricator.endlessm.com/T17614

Embedded videos are now normalized to image links

---

lib/assets/gallery-image-stylesheet.scss

The `.article-content` div moves with window expansion, but only when there
is not enough content to horizontally expand the div. This also causes
`.article-support` to expand.
Keep .article-support static, and left-align `.article-content`.
https://phabricator.endlessm.com/T18513

Correctly left-align .article-content

---

lib/index.js

This is used to specify the dates that the content might refer to
as opposed to the publication date of the article itself. The difference
is that the content dates should not be used for formatting, but they
might be useful for display.
https://phabricator.endlessm.com/T17886

gallery: Add a temoralCoverage field

---

package.json
previewer/main.html
previewer/package.json

New bootstrap doesn't specify jQ as a direct dep but as a peerDependecy so this is the workaround.

Fix bootstrap dep issue

---

lib/assets/gallery-image-article.mst
lib/assets/gallery-image-stylesheet.scss
lib/assets/gallery-video-article.mst
lib/assets/gallery-video-stylesheet.scss

The `.article-support` div that holds the original URI is too narrow.
- I gave it a little more width: 15vw to 20vw
- when there's nothing in the body of the content, the width of `.article-support` should be 100%, and the `.article-content` div is removed.
https://phabricator.endlessm.com/T18790

Libingester: Fix wrapping problem for article-support in Gallery Articles

---

lib/index.js

The vast majority of the time libingester is invoked (i.e. on SOMA by
libingester-worker) the dir is created, giving spurious warnings on each
run

Don't warn when output dir exists

---

examples/word_of_day.js

This word_of_day ingester is nearly identical to the quote_of_day ingester, save for the DictrionaryAsset class  and the expected changes in Cheerio CSS selectors.

Update word_of_day ingester with DictionaryAsset

---

lib/index.js
package.json
test/lib/index.test.js

Seems we've had the wrong name for this field set all along.
https://phabricator.endlessm.com/T19297

datePublished => published

---

lib/util.js
package.json

Since parameterizing these over the command line would necessitate
manual changes to every single ingester script, let's just use the
environment.
https://phabricator.endlessm.com/T19959

Allow RSS enty values to be overridden

---

lib/assets/gallery-video-stylesheet.scss
package.json

Restricts the header image in the gallery video article page from becoming too tall (particularly if the preview image is too tall). Design QA done by me.
Missed this in my last PR done on the header image CSS.
https://phabricator.endlessm.com/T20039

Fix GalleryVideo header image size restriction

---

lib/assets/_base.scss
package.json

The CSS for the article title was incorrectly styled as $primary-dark-color. (I think this was actually in an earlier design spec, which was a mistake.) It should be $primary-medium-color. Caught this while QA-ing various apps that had the incorrect title colors.

Article CSS: Changing title color base to $primary-medium-color

---

lib/assets/gallery-image-stylesheet.scss
lib/assets/gallery-video-stylesheet.scss
package.json

The previous selector would apply the rule to the social sharing icons,
which would mess up their padding because they were given a width of 100%.
https://phabricator.endlessm.com/T20019

gallery: Make img selector more specific

---

lib/assets/_colors.scss
package.json

This $primary-medium-color is the same color definition as the colors in the Endless SDK.

Add $primary-medium-color to _colors.scss & Bump libingester version

---

lib/index.js
package.json
test/lib/index.test.js

Unify the API across all different asset types. The exception is
NewsArticle, for which we only allow one tag as the section.
https://phabricator.endlessm.com/T20295

Allow to set tags to any asset

---

lib/util.js
package.json

Apparently mimetypes, while traditionally written as lower-case, are
actually case-insensitive.

download_image: fix case-sensitive matching

---

lib/index.js
package.json
test/lib/index.test.js

Old code would break on trying to set empty synopsis. This change now
makes sure that we don't do that since the synopsis is optional anyways.

Fix issues with trying to set empty synopsis

---

lib/index.js
package.json

There are now EKN templates able to sort sets and articles using the
sequenceNumber metadata.  This is useful for static ingesters.  For
example, to create videos lesson apps.
Example app already using this metadata:
https://github.com/endlessm/eos-subscriptions-apps/blob/master/com.endlessm.math.vi/content/db.json

index: add setter for sequenceNumber metadata

---

previewer/css/styles.css
previewer/main.html
previewer/main_renderer.js

As a regular user of libingester-previewer, I find a bit confusing to
see the selected row in the sidebar, because of the striped rows.  It
also makes the text bold in the selected row, resizing the text and
flickering because often the line number changes.
This commit removes striped rows, and uses the bootstrap class to make
rows active.

previewer: Improve sidebar usability

---

lib/util.js
package.json
test/lib/util.test.js

iconv-lite is possible to install without having to build native code.
Minor version bump instead of micro, because it's possible that an
ingester might be using an esoteric encoding that isn't supported by
iconv-lite.
https://phabricator.endlessm.com/T20985

util: Use iconv-lite instead of node-iconv

---

lib/util.js
package.json
test/lib/util.test.js

We don't need to use iconv at all, as long as we stick to NodeJS's built-in encodings.
https://phabricator.endlessm.com/T20985

Fixes for iconv

---

package.json
test/lib/util.test.js

By bumping Mocha dependency to v4 and increasing the timeout of the
'fetch_html' tests from 2 seconds (default) to 5 seconds.
The function in 'fetch_html' is changed because arrow functions are
discouraged in Mocha: https://mochajs.org/#arrow-functions

tests: make tests pass more often

---

docs/index.html
lib/index.js
package.json

This class is just a wrapper on top of `VideoAsset` which retains the "authors" metadata. It should be preferred over `GalleryVideoArticle` because it doesn't interpose a wrapper page, which was proving problematic for the apps.
https://phabricator.endlessm.com/T20761

T20761: Add VideoArticle

---

lib/index.js

Turns out that there is actually a use for this, in particular, for
videos that need some sort of surrounding context.
https://phabricator.endlessm.com/T20761

index: Undeprecate GalleryVideoArticle

---

lib/index.js
lib/verify.js

Previously, any metadata set on a VideoAsset was discarded.
https://phabricator.endlessm.com/T21578

Save video metadata to the hatch as well

---

lib/index.js

When metadata was added for videos in a1d42969, the canonical URI and
matching links became mandatory.  This fallbacks both to the download
URI.
https://phabricator.endlessm.com/T21734

Video metadata: fallbacks for canonical URI and matching links

---

lib/util.js

For errors 'Unexpected end' and 'Not a feed' thrown by the FeedParser
library.
https://phabricator.endlessm.com/T21793

util: RSS fetch: Add retry with exponential backoff

---

lib/util.js
package-lock.json
package.json
test/lib/test_files/rss-feeds.json
test/lib/util.test.js

Also fix bugs in pagination: arrays respecting MAX_DAYS_OLD only for
the first item.  Added unit tests.  Also added a number of dev
dependencies to stub the test feeds:
- sinon and rewire in combination to stub the _fetch_rss_json()
private function.
- sinon.useFakeTimers() to stub the global Date object.
- json-date-parser to obtain Date objects when parsing the json file.
https://phabricator.endlessm.com/T21642

util: Atomatically paginate Wordpress feeds

---

lib/verify.js

With new linting rules we can now improve the verification module.
Additional fixes to structure and standards were done as well along with
sturdier assert logic.

Linting and structure improvements to lib/verify.js

---

lib/config.js
test/lib/config.test.js

Merge the options passed to the Hatch constructor with the options
passed in the command line.
The original behaviour was to fully override the command line options
with the options passed to the Hatch constructor.
Added tests for command line options.  The config documentation is now
a bit easier to read.
https://phabricator.endlessm.com/T22232

config: Change behaviour of settings passed to Hatch

---

lib/util.js
package-lock.json
package.json

If by looking at the content-type returned by the server fails to
identify an image, try check if it's an image by looking at the
content.
Adds a new dependency lib, image-type.
https://phabricator.endlessm.com/T22412

util_download_image(): Improve check for content-type

---

lib/index.js
lib/util.js

To handle HTTP response errors and mark the Article assets
corresponding to the failing URL as failed.  This way the assets are
accounted in the % of failed assets.  Typical usage is:
function ingest_article(hatch, uri) {
return libingester.util.fetch_news_article(hatch, uri).then(({ $, asset }) => {
if (asset.has_failed()) {
return;
}
// normal article ingestion
});
}
https://phabricator.endlessm.com/T22195

util: Add new utils fetch_news_article(), fetch_blog_article()

---

lib/util.js

To avoid cloning the image element as it can conflict with the
cleanup.

util: download_img, use Cheerio wrap

---

lib/asset/baseAsset.js

This is going to break compatibility with the current hatch structure.
But it's really needed to save a considerable amount of memory on big
ingesters (encyclopedia).
FTR, the title from the manifest file is not actually used in SOMA.

Don't save the title in the manifest

---

lib/config.js
lib/ingester.js

RC will be 0 for none assets failed, 1 for many assets failed, 13 for
some assets failed. The failure rate threshold is configurable, and
defaults to 90% of the assets.
By default the ingester run() will exit the process. Passing exit =
false you can skip this.
https://phabricator.endlessm.com/T23489

Ingester: log total / failed, and exit accordingly

---

lib/asset/baseAsset.js
lib/asset/verifier.js
test/lib/asset/blogArticle.test.js

Sometimes the revisionTag can be another value rather than just the last
modified date (like the ETag or something like that), let's allow the
ingester to override the revisionTag for the asset.
Also, since the Soma pipeline is adding support to calculate the
revisionTag using hashing, let's allow the ingester to not specify
the revisionTag at all, so it's calculated down the pipeline.

Make revisionTag optional and allow to override it
