- lib/util.js
Some websites refuse to serve content to requests without one, and also
it's just good manners.
> Add user agent

- .gitignore
- package.json
- previewer/assetlist.html
- previewer/assetlist_renderer.js
- previewer/bin/hatch-preview
- previewer/main.js
- previewer/metadata.html
- previewer/metadata_renderer.js
- previewer/package.json
- previewer/preview.html
- previewer/preview_renderer.js
https://phabricator.endlessm.com/T16297
> SOMA: Add preview app to libingestor

- examples/old_indonesia.js
- examples/olympic.js
- examples/voa.js
- lib/index.js
- lib/util.js
https://phabricator.endlessm.com/T16359
> Libingester: Added a test case for wowshack and cleaned up the code a bit

- package.json
- previewer/assetlist.html
- previewer/assetlist_renderer.js
- previewer/bin/hatch-preview
- previewer/main.js
- previewer/metadata.html
- previewer/metadata_renderer.js
- previewer/package.json
- previewer/preview.html
- previewer/preview_renderer.js
https://phabricator.endlessm.com/T16343
> Libingester: Add source/page flipping and image previewing

- lib/util.js
- test/lib/util.test.js
**DO NOT MERGE BEFORE https://github.com/endlessm/libingester/pull/10** (test code file reorg is in it)
https://phabricator.endlessm.com/T16672
> Libingester added support for gzipped responses

- examples/quote_of_day.js
- examples/quote_of_day_template.js
I modified the already merged 'word_of_day' ingester and template to target quote content from FreeDictionary.
> Added ingester and template for 'quote_of_day' content.

- examples/day_in_history.js
- examples/day_in_history_template.js
Similar pull request as made in #19, however this one is targetting different content and this PR also keeps in mind the requested changes from #19 (code formatting).
> Add ingester and template for 'day_in_history' content.

- examples/holiday_of_day.js
- examples/holiday_of_day_template.js
This is the last of 4 ingesters based on FreeDictionary.com content. There are also a few minor tweaks to the 'day_in_history' ingester and template.
> Add 'holiday_of_day' ingester and template.

- lib/index.js
- package.json
Will wrote this, I just rebased and checked the output format. :)
> Output a tarball for a hatch

- lib/index.js
- test/lib/index.test.js
https://phabricator.endlessm.com/T16665
> NewsArticle: enable static tag

- previewer/css/styles.css
- previewer/main_renderer.js
This should make it easier to see the images without even clicking on
them.
> Added image thumbnails to asset list

- examples/ars.js
- examples/package.json
- lib/assets/news-article.mst
- lib/index.js
- package.json
- test/lib/index.test.js
This introduces the "standard" article format for NewsArticle. This
allows ingesting news articles in a way that can easily be styled
uniformly, with minimal stylesheet changes in between apps.
https://phabricator.endlessm.com/T17174
> NewsArticle: Switch to article format

- examples/livingloving.js
- lib/assets/blog-article.mst
- lib/index.js
- test/lib/index.test.js
Introduces a new BlogArticle asset class which
provides a simple API and template to generate
blog articles.
https://phabricator.endlessm.com/T17173
> Add blog article format

- lib/assets/blog-stylesheet.scss
- lib/index.js
- previewer/metadata_renderer.js
- test/lib/index.test.js
Includes other minor fixes.
https://phabricator.endlessm.com/T17569
> More metadata in previewer

- lib/assets/blog-article.mst
- lib/assets/blog-stylesheet.scss
- lib/assets/news-article.mst
- lib/assets/news-stylesheet.scss
Design QA for blog & news article stylesheets.
Remaining question: I'd like for the blog articles to also be able to have the large quote SVG when there's a `<blockquote>`, same as the news, but am not familiar enough with libingester to be able to test if it worked. @tchx84 could you help me with this?
> T17615 - Design QA for blog/news article stylesheets

- examples/ars.js
- examples/day_in_history.js
- examples/holiday_of_day.js
- examples/livingloving.js
- examples/old_indonesia.js
- examples/olympic.js
- examples/quote_of_day.js
- examples/voa.js
- examples/word_of_day.js
- lib/index.js
- lib/util.js
- previewer/main.js
- test/lib/index.test.js
- test/lib/util.test.js
Also fixed nodev5 compat and some ingesters.
Need to update wiki after completion. Also needs to stay in dev for e-c-f ingester changes to support this.
https://phabricator.endlessm.com/T17163
> Libingester: Add language as the constructor param for Hatch

- package.json
- previewer/css/styles.css
- previewer/main.html
- previewer/main.js
- previewer/main_renderer.js
- previewer/package.json
- previewer/preview_renderer.js
This was not helpful as-is so we now make sure that it's formated as
nicely as we can get it to be useful.
https://phabricator.endlessm.com/T17923
> Libingester: Added pretty-printing of the html in the source view

- lib/util.js
- package.json
https://phabricator.endlessm.com/T18105
> fetch_html: allow for content-type overrides

- lib/assets/gallery-image-article.mst
- lib/assets/gallery-image-stylesheet.scss
- lib/index.js
Article format + SCSS for gallery image article page
https://phabricator.endlessm.com/T17969
> Article format and stylesheet for standalone image article page

- lib/assets/blog-article.mst
- lib/assets/gallery-image-article.mst
- lib/assets/news-article.mst
- package.json
https://phabricator.endlessm.com/T17668
> templates: tag all main images as 'important' so they're not compressed

- lib/util.js
- package.json
https://phabricator.endlessm.com/T17414
> Use iconv for converting between charsets

- package.json
Since we have new styling, we need a bumped version on npm.
> Bumped version from 2.2.9 to 2.2.10

- lib/assets/gallery-video-article.mst
- lib/assets/gallery-video-stylesheet.scss
- lib/index.js
Article format + SCSS for gallery video article page
https://phabricator.endlessm.com/T18116
> Article format and stylesheet for standalone video article page

- lib/index.js
https://phabricator.endlessm.com/T18642
> T18642 (sanitize title and synopsis)

- lib/assets/gallery-image-article.mst
- lib/assets/gallery-video-article.mst
- package.json
- Fixed the incorrect div class selection when article-content is empty (should be article-support, not article-title)
https://phabricator.endlessm.com/T18790
> Libingester: Gallery Articles: article-support div full-width

- lib/index.js
- lib/verify.js
- package.json
https://phabricator.endlessm.com/T17825
> Add a number of sanity checks for content

- lib/assets/dictionary-article.mst
- lib/index.js
- lib/verify.js
- previewer/main_renderer.js
- previewer/metadata_renderer.js
Added a "DictionaryAsset" to index.js. This will support the "DictionaryObject" data model that is for DiscoveryFeed. I also added some related tests in verify.js.
https://phabricator.endlessm.com/T17329
> Dictionary object model

- lib/index.js
I overlooked a few methods that DictionaryAsset should probablly have.
> Dictionary object changes

- lib/assets/blog-article.mst
- lib/assets/gallery-image-article.mst
- lib/assets/gallery-video-article.mst
- lib/assets/news-article.mst
- package.json
- previewer/main.js
- previewer/preview_renderer.js
https://phabricator.endlessm.com/T18968
> Add video resource placeholders

- lib/assets/blog-article.mst
- lib/assets/gallery-image-article.mst
- lib/assets/news-article.mst
https://phabricator.endlessm.com/T19138
> Embed all main_images in ImageLinks

- package.json
We need this for the latest functionality changes to be published to
npm.
> Bump package version to 2.2.19

- lib/index.js
- package.json
https://phabricator.endlessm.com/T19171
> normalize all tags before saving them

- lib/assets/_base.scss
- lib/assets/_colors.scss
- lib/assets/_typography.scss
- lib/assets/blog-article.mst
- lib/assets/blog-stylesheet.scss
- lib/assets/gallery-image-stylesheet.scss
- lib/assets/gallery-video-stylesheet.scss
- lib/assets/news-article.mst
- lib/assets/news-stylesheet.scss
- package.json
Article pages: Create partials that contain shared CSS properties. Read commit for more information.
I put this all in 1 commit because there are a few moving parts that had to be done in one go.
Design QA was done by me.
https://phabricator.endlessm.com/T19470
> Article pages: Create partials that contain shared CSS properties

- lib/assets/gallery-video-article.mst
- lib/index.js
- package.json
- test/lib/index.test.js
https://phabricator.endlessm.com/T19215
> GalleryVideoArticle: more fixes for video thumbnails

- lib/assets/_media_link.scss
- lib/assets/gallery-video-stylesheet.scss
- package.json
- header image on article page: horizontally center the image
- cursor: pointer for hover state of header image
- bump libingester version
> Galleryvideo: Play button CSS tweaks

- lib/index.js
https://phabricator.endlessm.com/T19515
> Set isToplevel attribute for videos too

- lib/assets/gallery-video-article.mst
- lib/assets/gallery-video-stylesheet.scss
- package.json
Found that some images weren't expanding to a width of 100% if they were too small.
> Galleryvideo main image: Header image width 100%

- lib/index.js
- package.json
https://phabricator.endlessm.com/T19357
> Content body: remove target _blank from links

- previewer/css/styles.css
- previewer/main.html
- previewer/main.js
- previewer/main_renderer.js
https://phabricator.endlessm.com/T19174
> hatch-preview: give a simple breakdown of tag usage

- lib/assets/blog-stylesheet.scss
- lib/assets/gallery-video-stylesheet.scss
- lib/assets/news-stylesheet.scss
https://phabricator.endlessm.com/T20371
> Remove body bottom margin from news, blog and gallery templates

- README.md
- docs/index.html
- package.json
https://phabricator.endlessm.com/T21011
> README: Add link to API docs

- package.json
- previewer/package.json
There were some security fixes and usability features added.
> Upgraded Electron to latest version for previewer

- docs/index.html
- lib/index.js
- lib/util.js
- package.json
Documents some more API entry points that I'm using in the ingester walkthrough.
https://phabricator.endlessm.com/T20978
> Document more

- lib/util.js
- package.json
To reuse the logic of util.fetch_rss_entries() in the ingesters, and
do the environment variable parsing in one place.
https://phabricator.endlessm.com/T20341
> new API get_max_settings()

- lib/util.js
https://phabricator.endlessm.com/T21578
> Improve util.get_embedded_video_asset()

- lib/index.js
- package.json
Only minimal code cleanup for now since node v8 support is much more important.
https://phabricator.endlessm.com/T21994
> Pin to Node v8 and minor clean up of some of the old code

- README.md
Added instructions for linting files in the repository.
> Added linting instructions to README

- lib/util.js
- test/lib/util.test.js
Fixed majority of linting erros, converted internal representation to
camelCase, fixed inefficiencies, and updated tests to match.
> Improved linting and structure of lib/util.js

- lib/index.js
- test/lib/index.test.js
Linting and structure improvements all around and general cleanup of
obvious code smells.
> Various improvements to lib/index.js

- lib/util.js
https://phabricator.endlessm.com/T22285
> util: Add retry for dns.js ENOTFOUND error

- lib/asset/baseAsset.js
- test/lib/index.test.js
https://phabricator.endlessm.com/T21992
> Hatch: Throw validation error saving same asset twice

- data/assets/news-stylesheet.scss
This will be used when the news article is
displayed on the Endless Companion.
https://phabricator.endlessm.com/T22922
> News-sylesheet: add support for mobile devices

- lib/asset/baseAsset.js
- lib/asset/blogArticle.js
- lib/asset/dictionaryAsset.js
- lib/asset/galleryImageArticle.js
- lib/asset/galleryVideoArticle.js
- lib/asset/imageAsset.js
- lib/asset/newsArticle.js
- lib/asset/videoArticle.js
- lib/asset/videoAsset.js
- test/lib/asset/blogArticle.test.js
- test/lib/asset/galleryImageArticle.test.js
- test/lib/asset/galleryVideoArticle.test.js
- test/lib/asset/imageAsset.test.js
- test/lib/asset/newsArticle.test.js
- test/lib/asset/videoArticle.test.js
- test/lib/asset/videoAsset.test.js
- test/lib/index.test.js
- test/lib/util.test.js
https://phabricator.endlessm.com/T22483
> Allow setting multiple fields at once

- lib/util.js
- test/lib/test_files/article_cleaned.html
- test/lib/test_files/article_cleaned_custom.html
- test/lib/test_files/article_to_clean.html
- test/lib/util.test.js
https://phabricator.endlessm.com/T22968
> util: Add utility function to clean articles body

- lib/asset/baseAsset.js
- lib/asset/blogArticle.js
- lib/asset/dictionaryAsset.js
- lib/asset/galleryImageArticle.js
- lib/asset/galleryVideoArticle.js
- lib/asset/imageAsset.js
- lib/asset/newsArticle.js
- lib/asset/util.js
- lib/asset/verifier.js
- lib/asset/videoArticle.js
- lib/asset/videoAsset.js
- lib/config.js
- lib/errors.js
- lib/logging.js
- lib/util.js
- test/lib/asset/blogArticle.test.js
- test/lib/asset/imageAsset.test.js
- test/lib/asset/newsArticle.test.js
- test/lib/asset/verifier.test.js
- test/lib/config.test.js
- test/lib/index.test.js
- test/lib/test_files/article_to_clean.html
- test/lib/util.test.js
https://phabricator.endlessm.com/T22968
> More cleanup

- lib/util.js
- test/lib/test_files/article_cleaned.html
- test/lib/test_files/article_cleaned_custom.html
- test/lib/test_files/article_to_clean.html
With an exception for the data-soma-* and data-libingester-*
attributes.
https://phabricator.endlessm.com/T22968
> util: Remove custom data attributes in cleanup_body

- lib/asset/baseAsset.js
- lib/asset/videoAsset.js
- lib/index.js
https://phabricator.endlessm.com/T23183
> T23183 fixmemory

- lib/util.js
https://phabricator.endlessm.com/T23324
> util.fetch_rss_entries: Skip items without a link

- data/assets/_base.scss
https://phabricator.endlessm.com/T22872
> Stylesheets: basic print stylesheet

- lib/util.js
It was creating the asset, but not embedding it in the body.
https://phabricator.endlessm.com/T23320
> download_img util: Fix case for data src

- lib/asset/verifier.js
- lib/index.js
https://phabricator.endlessm.com/T23549
> T23549 expose baseasset

- lib/html-article-parser.js
- lib/processors/index.js
- lib/processors/normalize-headers-processor.js
https://phabricator.endlessm.com/T23759
> Normalize headers processor

- lib/asset/blogArticle.js
- lib/asset/dictionaryAsset.js
- lib/asset/newsArticle.js
- lib/asset/util.js
- lib/asset/verifier.js
- lib/index.js
- lib/util.js
https://phabricator.endlessm.com/T23767
> T23767 libingester fixlinks

- lib/html-article-parser.js
- lib/processors/image-embeds.js
- lib/processors/index.js
- lib/processors/twitter-embeds.js
https://phabricator.endlessm.com/T23952
> Add twitter embeds processor

- lib/html-article-parser.js
- lib/processors/index.js
- lib/processors/instagram-embeds.js
- lib/processors/twitter-embeds.js
https://phabricator.endlessm.com/T23952
> Add instagram embeds processor

- lib/asset/baseAsset.js
- lib/asset/pdfAsset.js
- lib/index.js
- test/lib/asset/pdfAsset.test.js
https://phabricator.endlessm.com/T25706
> Add PdfAsset, along with can_export and can_print metadata

- lib/asset/verifier.js
https://phabricator.endlessm.com/T28066
> verifier: Add AudioObject support
